<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="QuestPDF" Version="2026.6.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ipma.Domain\Ipma.Domain.csproj" />
      <ProjectReference Include="..\Ipma.Infrastructure\Ipma.Infrastructure.csproj" />
    </ItemGroup>

</Project>
