// <auto-generated />
using System;
using Ipma.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ipma.Infrastructure.Migrations
{
    [DbContext(typeof(IpmaDbContext))]
    [Migration("20260624170701_AddAccountForBiuroNagrody")]
    partial class AddAccountForBiuroNagrody
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CzłonekJuryEdycjaKonkursu", b =>
                {
                    b.Property<Guid>("CzłonkowieJuryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OcenianeKonkursyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CzłonkowieJuryId", "OcenianeKonkursyId");

                    b.HasIndex("OcenianeKonkursyId");

                    b.ToTable("CzłonekJuryEdycjaKonkursu");
                });

            modelBuilder.Entity("EdycjaKonkursuKategoria", b =>
                {
                    b.Property<Guid>("EdycjeKonkursuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KategorieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EdycjeKonkursuId", "KategorieId");

                    b.HasIndex("KategorieId");

                    b.ToTable("EdycjaKonkursuKategoria");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Commons.KontoUżytkownika", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Hasło")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rola")
                        .HasColumnType("int");

                    b.Property<bool>("StatusKonta")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("KontoUżytkownika");

                    b.HasDiscriminator<string>("Discriminator").HasValue("KontoUżytkownika");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Ipma.Domain.Entities.EdycjaKonkursu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NumerEdycji")
                        .HasColumnType("int");

                    b.Property<Guid?>("PrzewodniczącyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RokKalendarzowy")
                        .HasColumnType("int");

                    b.Property<int>("StatusRealizacji")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PrzewodniczącyId");

                    b.ToTable("EdycjeKonkursu");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.EkspertIpma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("FlagaKonfliktuInteresów")
                        .HasColumnType("bit");

                    b.Property<int>("RokUkończeniaSzkoleńPeb")
                        .HasColumnType("int");

                    b.Property<string>("StatusDostępności")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UmowaWspółpracyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("UmowaWspółpracyId")
                        .IsUnique()
                        .HasFilter("[UmowaWspółpracyId] IS NOT NULL");

                    b.ToTable("EksperciIpma");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Harmonogram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataDrugiegoPosiedzeniaJury")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataGaliFinałowej")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataOtwarciaAplikacji")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataPierwszegoPosiedzeniaJury")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWebinariumAplikantow")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWebinariumAsesorow")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWebinariumAsesorowWiodacych")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataZamknięciaAplikacji")
                        .HasColumnType("date");

                    b.Property<Guid>("EdycjaKonkursuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("TerminWizytStudyjnych")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EdycjaKonkursuId")
                        .IsUnique();

                    b.ToTable("Harmonogramy");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Kategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.OcenaIndywidualna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsesorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("CzyOcenaSpozniona")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyZatwierdzona")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PlanowanaDataOpracowania")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UzasadnienieOceniajacego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WynikObszarLudzieICel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WynikObszarProcesyIZasoby")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WynikObszarRezultaty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AsesorId");

                    b.HasIndex("ProjektId");

                    b.ToTable("OcenyIndywidualne");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.OcenaKońcowa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("CzyOcenaSpozniona")
                        .HasColumnType("bit");

                    b.Property<double>("OstatecznaNotaPunktowa")
                        .HasColumnType("float");

                    b.Property<DateOnly>("PlanowanaDataOpracowania")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RekomendacjaFinałowa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UzasadnienieOceniajacego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WynikObszarLudzieICel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WynikObszarProcesyIZasoby")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WynikObszarRezultaty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId")
                        .IsUnique();

                    b.ToTable("OcenyKońcowe");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.OcenaWstępna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("CzyOcenaSpozniona")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyOsiągniętoKonsensus")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PlanowanaDataOpracowania")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SkonsolidowanyWynikPunktowy")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UzasadnienieOceniajacego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WynikObszarLudzieICel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WynikObszarProcesyIZasoby")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WynikObszarRezultaty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId")
                        .IsUnique();

                    b.ToTable("OcenyWstępne");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.OpłataZgłoszeniowa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataRejestracjiWpłaty")
                        .HasColumnType("date");

                    b.Property<decimal>("KwotaDoZapłatyNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatusTransakcji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WniosekAplikacyjnyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WniosekAplikacyjnyId")
                        .IsUnique();

                    b.ToTable("OpłatyZgłoszeniowe");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Projekt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AplikantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AsesorWiodącyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CzasTrwaniaWMiesiącach")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataUkończenia")
                        .HasColumnType("date");

                    b.Property<Guid>("EdycjaKonkursuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KategoriaWyróżnienia")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaPodwykonawców")
                        .HasColumnType("int");

                    b.Property<string>("MiejsceWizytyStudyjnej")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaPrzedsięwzięcia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StanKwalifikacji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UtworzonyPrzezId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WielkośćZespołu")
                        .HasColumnType("int");

                    b.Property<Guid>("ZmodyfikowanyPrzezId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ŚredniaOcenaCzłonkówJury")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AplikantId");

                    b.HasIndex("AsesorWiodącyId");

                    b.HasIndex("EdycjaKonkursuId");

                    b.HasIndex("KategoriaId");

                    b.HasIndex("UtworzonyPrzezId");

                    b.HasIndex("ZmodyfikowanyPrzezId");

                    b.ToTable("Projekty");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.RaportAplikacyjny", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataDostarczeniaFizycznego")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UtworzonyPrzezId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WykazZałączników")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ZmodyfikowanyPrzezId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId")
                        .IsUnique();

                    b.HasIndex("UtworzonyPrzezId");

                    b.HasIndex("ZmodyfikowanyPrzezId");

                    b.ToTable("RaportyAplikacyjne");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.RaportZWizyty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataZłożeniaDokumentu")
                        .HasColumnType("date");

                    b.Property<string>("KatalogOdpowiedziDlaJury")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UtworzonyPrzezId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZmodyfikowanyPrzezId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId")
                        .IsUnique();

                    b.HasIndex("UtworzonyPrzezId");

                    b.HasIndex("ZmodyfikowanyPrzezId");

                    b.ToTable("RaportyZWizyty");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.UmowaWspółpracy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataZawarciaKontraktu")
                        .HasColumnType("date");

                    b.Property<bool>("KlauzulaPoufności")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZakresPowierzonychZadań")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UmowyWspółpracy");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.WniosekAplikacyjny", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataWprowadzeniaDoSystemu")
                        .HasColumnType("date");

                    b.Property<bool>("FlagaZgodnościFormalnej")
                        .HasColumnType("bit");

                    b.Property<int>("NumerAplikacji")
                        .HasColumnType("int");

                    b.Property<string>("PowódOdrzucenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UtworzonyPrzezId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZmodyfikowanyPrzezId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId")
                        .IsUnique();

                    b.HasIndex("UtworzonyPrzezId");

                    b.HasIndex("ZmodyfikowanyPrzezId");

                    b.ToTable("WnioskiAplikacyjne");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Aplikant", b =>
                {
                    b.HasBaseType("Ipma.Domain.Entities.Commons.KontoUżytkownika");

                    b.Property<bool>("StatusCzłonkaIpma")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Aplikant");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Asesor", b =>
                {
                    b.HasBaseType("Ipma.Domain.Entities.Commons.KontoUżytkownika");

                    b.Property<Guid>("EkspertIpmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlagaUprawnieńZarządczych")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EkspertIpmaId")
                        .IsUnique()
                        .HasFilter("[EkspertIpmaId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Asesor");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.BiuroNagrody", b =>
                {
                    b.HasBaseType("Ipma.Domain.Entities.Commons.KontoUżytkownika");

                    b.Property<string>("AdresEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresKorespondencyjny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EdycjaKonkursuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("EdycjaKonkursuId")
                        .IsUnique()
                        .HasFilter("[EdycjaKonkursuId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("BiuroNagrody");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.CzłonekJury", b =>
                {
                    b.HasBaseType("Ipma.Domain.Entities.Commons.KontoUżytkownika");

                    b.Property<string>("AfiliacjaNaukowaLubBiznesowa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CzłonekJury");
                });

            modelBuilder.Entity("CzłonekJuryEdycjaKonkursu", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.CzłonekJury", null)
                        .WithMany()
                        .HasForeignKey("CzłonkowieJuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.EdycjaKonkursu", null)
                        .WithMany()
                        .HasForeignKey("OcenianeKonkursyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdycjaKonkursuKategoria", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.EdycjaKonkursu", null)
                        .WithMany()
                        .HasForeignKey("EdycjeKonkursuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Kategoria", null)
                        .WithMany()
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ipma.Domain.Entities.EdycjaKonkursu", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.CzłonekJury", "Przewodniczący")
                        .WithMany("PrzewodzoneKonkursy")
                        .HasForeignKey("PrzewodniczącyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Przewodniczący");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.EkspertIpma", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.UmowaWspółpracy", "UmowaWspółpracy")
                        .WithOne("EkspertIpma")
                        .HasForeignKey("Ipma.Domain.Entities.EkspertIpma", "UmowaWspółpracyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Ipma.Domain.Entities.Owned.DaneOsobowe", "DaneOsobowe", b1 =>
                        {
                            b1.Property<Guid>("EkspertIpmaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AdresEmail")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Imie")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nazwisko")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NrTelefonu")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EkspertIpmaId");

                            b1.ToTable("EksperciIpma");

                            b1.WithOwner()
                                .HasForeignKey("EkspertIpmaId");
                        });

                    b.Navigation("DaneOsobowe")
                        .IsRequired();

                    b.Navigation("UmowaWspółpracy");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Harmonogram", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.EdycjaKonkursu", "EdycjaKonkursu")
                        .WithOne("Harmonogram")
                        .HasForeignKey("Ipma.Domain.Entities.Harmonogram", "EdycjaKonkursuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EdycjaKonkursu");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.OcenaIndywidualna", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.Asesor", "Asesor")
                        .WithMany("OcenyIndywidualne")
                        .HasForeignKey("AsesorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Projekt", "Projekt")
                        .WithMany("OcenyIndywidualne")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asesor");

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.OcenaKońcowa", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.Projekt", "Projekt")
                        .WithOne("OcenaKońcowa")
                        .HasForeignKey("Ipma.Domain.Entities.OcenaKońcowa", "ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.OcenaWstępna", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.Projekt", "Projekt")
                        .WithOne("OcenaWstępna")
                        .HasForeignKey("Ipma.Domain.Entities.OcenaWstępna", "ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.OpłataZgłoszeniowa", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.WniosekAplikacyjny", "WniosekAplikacyjny")
                        .WithOne("OpłataZgłoszeniowa")
                        .HasForeignKey("Ipma.Domain.Entities.OpłataZgłoszeniowa", "WniosekAplikacyjnyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WniosekAplikacyjny");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Projekt", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.Aplikant", "Aplikant")
                        .WithMany("Projekty")
                        .HasForeignKey("AplikantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Asesor", "AsesorWiodący")
                        .WithMany("ProjektyNadzorowane")
                        .HasForeignKey("AsesorWiodącyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ipma.Domain.Entities.EdycjaKonkursu", "EdycjaKonkursu")
                        .WithMany("Projekty")
                        .HasForeignKey("EdycjaKonkursuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Kategoria", "Kategoria")
                        .WithMany("Projekty")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Commons.KontoUżytkownika", "UtworzonyPrzez")
                        .WithMany()
                        .HasForeignKey("UtworzonyPrzezId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Commons.KontoUżytkownika", "ZmodyfikowanyPrzez")
                        .WithMany()
                        .HasForeignKey("ZmodyfikowanyPrzezId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Ipma.Domain.Entities.Owned.PytanieOdJury", "PytaniaOdJury", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProjektId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Treść")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjektId");

                            b1.ToTable("PytanieOdJury");

                            b1.WithOwner()
                                .HasForeignKey("ProjektId");
                        });

                    b.Navigation("Aplikant");

                    b.Navigation("AsesorWiodący");

                    b.Navigation("EdycjaKonkursu");

                    b.Navigation("Kategoria");

                    b.Navigation("PytaniaOdJury");

                    b.Navigation("UtworzonyPrzez");

                    b.Navigation("ZmodyfikowanyPrzez");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.RaportAplikacyjny", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.Projekt", "Projekt")
                        .WithOne("RaportAplikacyjny")
                        .HasForeignKey("Ipma.Domain.Entities.RaportAplikacyjny", "ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Commons.KontoUżytkownika", "UtworzonyPrzez")
                        .WithMany()
                        .HasForeignKey("UtworzonyPrzezId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Commons.KontoUżytkownika", "ZmodyfikowanyPrzez")
                        .WithMany()
                        .HasForeignKey("ZmodyfikowanyPrzezId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projekt");

                    b.Navigation("UtworzonyPrzez");

                    b.Navigation("ZmodyfikowanyPrzez");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.RaportZWizyty", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.Projekt", "Projekt")
                        .WithOne("RaportZWizyty")
                        .HasForeignKey("Ipma.Domain.Entities.RaportZWizyty", "ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Commons.KontoUżytkownika", "UtworzonyPrzez")
                        .WithMany()
                        .HasForeignKey("UtworzonyPrzezId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Commons.KontoUżytkownika", "ZmodyfikowanyPrzez")
                        .WithMany()
                        .HasForeignKey("ZmodyfikowanyPrzezId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projekt");

                    b.Navigation("UtworzonyPrzez");

                    b.Navigation("ZmodyfikowanyPrzez");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.WniosekAplikacyjny", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.Projekt", "Projekt")
                        .WithOne("WniosekAplikacyjny")
                        .HasForeignKey("Ipma.Domain.Entities.WniosekAplikacyjny", "ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Commons.KontoUżytkownika", "UtworzonyPrzez")
                        .WithMany()
                        .HasForeignKey("UtworzonyPrzezId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ipma.Domain.Entities.Commons.KontoUżytkownika", "ZmodyfikowanyPrzez")
                        .WithMany()
                        .HasForeignKey("ZmodyfikowanyPrzezId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projekt");

                    b.Navigation("UtworzonyPrzez");

                    b.Navigation("ZmodyfikowanyPrzez");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Aplikant", b =>
                {
                    b.OwnsOne("Ipma.Domain.Entities.Owned.DaneOsobowe", "DaneOsobowe", b1 =>
                        {
                            b1.Property<Guid>("AplikantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AdresEmail")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Imie")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nazwisko")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NrTelefonu")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AplikantId");

                            b1.ToTable("KontoUżytkownika");

                            b1.WithOwner()
                                .HasForeignKey("AplikantId");
                        });

                    b.OwnsOne("Ipma.Domain.Entities.Owned.Organizacja", "Organizacja", b1 =>
                        {
                            b1.Property<Guid>("AplikantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("KodPocztowy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NazwaOrganizacji")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NumerNip")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SkrótNazwyOrganizacji")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AplikantId");

                            b1.ToTable("KontoUżytkownika");

                            b1.WithOwner()
                                .HasForeignKey("AplikantId");
                        });

                    b.Navigation("DaneOsobowe")
                        .IsRequired();

                    b.Navigation("Organizacja")
                        .IsRequired();
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Asesor", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.EkspertIpma", "EkspertIpma")
                        .WithOne("Asesor")
                        .HasForeignKey("Ipma.Domain.Entities.Asesor", "EkspertIpmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkspertIpma");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.BiuroNagrody", b =>
                {
                    b.HasOne("Ipma.Domain.Entities.EdycjaKonkursu", "EdycjaKonkursu")
                        .WithOne("BiuroNagrody")
                        .HasForeignKey("Ipma.Domain.Entities.BiuroNagrody", "EdycjaKonkursuId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("EdycjaKonkursu");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.CzłonekJury", b =>
                {
                    b.OwnsOne("Ipma.Domain.Entities.Owned.DaneOsobowe", "DaneOsobowe", b1 =>
                        {
                            b1.Property<Guid>("CzłonekJuryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AdresEmail")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Imie")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nazwisko")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NrTelefonu")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CzłonekJuryId");

                            b1.ToTable("KontoUżytkownika", t =>
                                {
                                    t.Property("AdresEmail")
                                        .HasColumnName("DaneOsobowe_AdresEmail1");

                                    t.Property("Imie")
                                        .HasColumnName("DaneOsobowe_Imie1");

                                    t.Property("Nazwisko")
                                        .HasColumnName("DaneOsobowe_Nazwisko1");

                                    t.Property("NrTelefonu")
                                        .HasColumnName("DaneOsobowe_NrTelefonu1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CzłonekJuryId");
                        });

                    b.Navigation("DaneOsobowe")
                        .IsRequired();
                });

            modelBuilder.Entity("Ipma.Domain.Entities.EdycjaKonkursu", b =>
                {
                    b.Navigation("BiuroNagrody")
                        .IsRequired();

                    b.Navigation("Harmonogram")
                        .IsRequired();

                    b.Navigation("Projekty");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.EkspertIpma", b =>
                {
                    b.Navigation("Asesor");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Kategoria", b =>
                {
                    b.Navigation("Projekty");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Projekt", b =>
                {
                    b.Navigation("OcenaKońcowa");

                    b.Navigation("OcenaWstępna");

                    b.Navigation("OcenyIndywidualne");

                    b.Navigation("RaportAplikacyjny");

                    b.Navigation("RaportZWizyty");

                    b.Navigation("WniosekAplikacyjny")
                        .IsRequired();
                });

            modelBuilder.Entity("Ipma.Domain.Entities.UmowaWspółpracy", b =>
                {
                    b.Navigation("EkspertIpma")
                        .IsRequired();
                });

            modelBuilder.Entity("Ipma.Domain.Entities.WniosekAplikacyjny", b =>
                {
                    b.Navigation("OpłataZgłoszeniowa");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Aplikant", b =>
                {
                    b.Navigation("Projekty");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.Asesor", b =>
                {
                    b.Navigation("OcenyIndywidualne");

                    b.Navigation("ProjektyNadzorowane");
                });

            modelBuilder.Entity("Ipma.Domain.Entities.CzłonekJury", b =>
                {
                    b.Navigation("PrzewodzoneKonkursy");
                });
#pragma warning restore 612, 618
        }
    }
}
